### PR TITLE
Feature/packaging

### PR DESCRIPTION
**Pull request by todorus**
Made some changes so we can create wheel files so the package can be used as a library in other projects.

### CODE REVIEW

**Review by Tilana — COMMENTED** [review]
(1) The standard way of initializing a python package is with an __initi__.py file in the directory, which in our case is newsAnalysis. http://mikegrouchy.com/blog/2012/05/be-pythonic-__init__py.html
It would require minor changes in the imports...
(2) What is the main advantage of packaging the code into a wheel? it seems to add on maintenance and testing work without a direct need/benefit at our current project state

**Comment by todorus** [comment]
1 No problem. This actually changes nothing about the imports in this case.
2 The code is a library of functionality that is used by other applications that need to interact with a model (the viewer, automated jobs etc), so it should be packaged for these other application to easily use it. This will greatly increase maintainability as this will include versioning and keeping all the model code in one project instead of copied and spread across the multiple applications. Basically the problems that packaging is designed to solve.

**Comment by Tilana** [comment]
2.1 Also when packaged the viewer will have to communicate with the model via API or in a different way...
2.2 Versions of required install packages are already kept track of in the requirements file (if that is what you mean by versioning...).

**Comment by Tilana** [comment]
I like that the PR reorganizes the repo to create newsanalysis module and extract the run script. Also having it ready as a package is super cool
However, I have my doubts about the necessity of building a wheel as it requires constant updates on new imported modules and of course time to test, and also I think a package provides similar advantages than a wheel as it can be imported easily.

**Comment by Tilana** [comment]
But if you think this will make our life easier at some point and benefit the project, let's go ahead and merge.

**Pull request merged**
